        anonymous:
        - job-read
        - job-extended-read
        qwandor-google:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel
        olivier.deprez:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel
        maksims.svecovs:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel
        joao.alves:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel