        anonymous:
        - job-read
        - job-extended-read
        qwandor-google:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel
        odeprez:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel
        max-shvetsov:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel
        J-Alves:
        - job-read
        - job-extended-read
        - job-build
        - job-cancel

